export { default as Activities } from './Activities'
export { default as AddRoutine } from './AddRoutine'
export { default as Header } from './Header'
export { default as Login } from './Login'
export { default as MyRoutines } from './MyRoutines'
export { default as Navbar } from './Navbar'
export { default as Register } from './Register'
export { default as Routines } from './Routines'
